name: dart_html_limit_perf_test
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  benchmark_harness: ^2.0.0
  http: ^0.13.3
#  html: ^0.15.0
  html:
    git:
      url: https://github.com/mzdm/html.git
      ref: feat/limit-query-param

dev_dependencies:
  pedantic: ^1.10.0
